# List of Modules
# By default, all integrations are disabled. You must enable them manually when needed.
# Requires a restart to take effect.
# --------------------------------------------------------------------------------------
modules:
  mysql: false
  worldguard: false
  vault: false
  realistic_seasons: false
# --------------------------------------------------------------------------------------

# MySQL Database - required for vSkills.
# Requires a restart to take effect.
# --------------------------------------------------------------------------------------
mysql:
  host: localhost
  port: 3306
  username: root
  password: root
  database: vlib_db
# --------------------------------------------------------------------------------------